build.gradle
gradle/publish.gradle
src/main/java/module-info.java

Apply [gradle-modules-plugin](https://github.com/java9-modularity/gradle-modules-plugin) and replace existing configurations with [`modularity.mixedJavaRelease` which configures `--release` javac option](https://github.com/java9-modularity/gradle-modules-plugin#separate-compilation-of-module-infojava).
close #104
```
Classfile .../jspecify/build/libs/module-info.class
Last modified Apr 26, 2020; size 204 bytes
MD5 checksum e57e5ad61b984f5ef27b6583a6230f74
Compiled from "module-info.java"
module jspecify.annotations
minor version: 0
major version: 53
```
Major version 53 means Java 9.
```
Classfile .../jspecify/build/libs/org/jspecify/experimentaldonotuse/Nullable.class
Last modified Apr 26, 2020; size 443 bytes
MD5 checksum 3457a0b34780144765f79960198c4c42
Compiled from "Nullable.java" …
```

Define a JPMS module for our annotations

---

.github/workflows/build.yml
build.gradle
gradle/publish.gradle
src/main/java/module-info.java
src/main/java/org/jspecify/annotations/DefaultNonNull.java
src/main/java/org/jspecify/annotations/Nullable.java

Based on [this proposal](https://github.com/jspecify/jspecify/issues/1#issuecomment-620826847), rename package and module to `org.jspecify.annotations`.
In this branch, we can build and publish artifacts `org.jspecify:annotations:0.1.0-SNAPSHOT` like below:
```
$ ./gradlew publishToMavenLocal
$ ls -1R ~/.m2/repository/org/jspecify
annotations
~/.m2/repository/org/jspecify/annotations:
0.1.0-SNAPSHOT
maven-metadata-local.xml
~/.m2/repository/org/jspecify/annotations/0.1.0-SNAPSHOT:
annotations-0.1.0-SNAPSHOT-javadoc.jar
annotations-0.1.0-SNAPSHOT-sources.jar
annotations-0.1.0-SNAPSHOT.jar
annotations-0.1.0-SNAPSHOT.module
annotations-0.1.0-SNAPSHOT.pom
maven-metadata-local.xml
```

Rename package and module, to prepare for install and deploy

---

docs/index.rst
docs/locale/ja/LC_MESSAGES/index.po

This change adds a link to [the slide shared at JVMLS19](https://docs.google.com/presentation/d/1zmblWc_S9LrmKq8VH8p_eb7H31rTYoNFVbutnXPyolM/edit?usp=sharing).
Also applies a tiny fix, to make a header intuitive.

Add a link to the slide

---

.github/workflows/docs.yml

We changed the default branch from `master` to `main`, so we need to use `main` in the `docs.yml` file.

Update the target branch name to build

---

docs/index.rst

[The newly added page](https://jspecify.dev/tsttcpw.html) is not linked from the site top.
This PR suggests to link it from the side menu.

Link to the new page from the site top

---

.github/workflows/docs.yml

in an attempt to fix https://github.com/jspecify/jspecify/runs/1200508024
(And to see whether the CLA works.)
Not sure whether this is the right fix, though.

Use fixed github-pages-deploy-action version

---

samples/AnnotatedReceiver.java

Receiver should be considered categorically non-nullable.
Not super sure I'm using the right error codes here so please review carefully.

add sample with annotated receiver

---

samples/NullCheck.java
samples/NullCheckTypeVariable.java

These test cases mandate a false positive warning in correct code.
We don't want our test cases to contain false positive warnings that not all checkers will issue.
In the future, they could be added with a different (non-normative) tag.  In the meanwhile, I think it is better to remove them rather than have a broken test suite.

Remove false positive warnings

---

gradle/mrjar.gradle

This handles the Javadoc half of https://github.com/jspecify/jspecify/issues/179

For Javadoc jar, prefer Java 9+ sources over Java 8.

---

docs/conf.py
docs/design-overview.md
docs/spec.md

This PR suggests fixing several warnings and duplicated word in the doc:
1. Stop building `README.md` as a part of the landing page; now it's available at https://jspecify.dev/README.html
2. Remove duplicated reference `CONTAINMENT` in `spec.md` and `design-overview.md`
3. Remove duplicated "genearte "
Thanks for your review! :)

Resolve warning of the document generation with markdown

---

src/java9/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/Nullable.java
src/main/java/org/jspecify/nullness/NullnessUnspecified.java

I want to propose keeping the javadoc as short as possible, just for 0.2.0. Here is one take on that.

Candidates for minimalist javadoc in 0.2.0

---

samples/README.md
src/java9/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/Nullable.java

How do people feel about using `jspecify.org` for links, to be consistent with the package name?
The link will automatically redirect to `jspecify.dev`.
(Also needs to be done in other files.)

Use jspecify.org

---

src/main/java/org/jspecify/nullness/NullMarked.java

There already is a reference from Nullable to NullMarked.
(Java 9+ version also needs this edit. Didn't reformat to highlight change.)

Link Nullable from NullMarked.

---

src/java9/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/Nullable.java

Instead of just warning about "libraries", should it be something more general, like "projects"?
Libraries are particularly affected, as others also depend on them. But the warning equally applies to somebody who just uses the annotations in their application.

Generalize warning

---

gradle/publish.gradle

Instructions:
https://docs.gradle.org/current/userguide/publishing_maven.html#sec:modifying_the_generated_pom
Without this, we can't close the Sonatype repository: We get the error
"Developer information missing."
It's not clear who exactly we should list here. Probably we'd prefer
that people contact us on GitHub or our mailing list (if we've opened up
posting permission to everyone). For the moment, I've added only kevinb,
since he has plans to do some outreach to the wider community. If anyone
would like to be added, feel free to add yourself.

Add a `developer` to the project metadata.

---

docs/user-guide.md

Several other issues have also been addressed. Here the main changes:
* Avoided using `String` to mean both a reference of that type and an object of that type.
Now we say "variable of type `String`" and we say "string object" when we mean an object of that type.
* Reworded text that was implicitly talking about unspecified nullness so that it explicitly
says that JSpecify doesn't say anything about the possible nullness of a non-`@Nullable` type
outside `@NullMarked`.
* Removed claim that null-annotating everything is a "goal" of JSpecify in favour of saying that
JSpecify can help with it.
* Explicitly introduced the notion that `String` is a subtype of `@Nullable String` early on.
* Removed some `public` and `static` keywords from examples where they were basically noise.
* Changed an …

User guide changes to address the issues in #203.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

I tried building with the current JDK 17 release candidate and get an exception:
````
* What went wrong:
Could not compile settings file '/home/wdietl/Sync/wmdietl/workspaces/jspecify/jspecify/settings.gradle'.
> startup failed:
General error during conversion: Unsupported class file major version 61
java.lang.IllegalArgumentException: Unsupported class file major version 61
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:189)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:170)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:156)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:277)
````
The changes in this PR update gradle to 7.2 and update some plugin versions.
This now builds successfully with the JDK 17 RC1.
There are some deprecation …

Allow build with JDK 17

---

build.gradle

Now builds in `main` print several warnings caused by the Gradle Modules plugin. It was introduced by Gradle v7.2 introduced by 6c3f28650dcb3843965f9691f05aa624ec300e56. So I've investigated and found a solution: java9-modularity/gradle-modules-plugin#201
The [updated version](https://github.com/java9-modularity/gradle-modules-plugin/releases/tag/v1.8.9) has been released yesterday, so I'm suggesting this PR that applies the released version to remove warnings. I've confirmed that this change has removed warnings during the build in [this workflow run](https://github.com/jspecify/jspecify/runs/3501654400).

Remove build warnings introduced by Gradle 7.2

---

.github/workflows/build.yml
.github/workflows/docs.yml

Just minor updates for the workflows:
1. Apply the built-in cache feature of `actions/setup-java` to shorten the workflow definition. It's also expected to reduce the time to build. refs https://github.com/actions/setup-java/pull/193#issuecomment-901865758
2. `amesIves/github-pages-deploy-action` released v4, so followed its [migration guide](https://github.com/JamesIves/github-pages-deploy-action/discussions/592) to get updated and secure.
3. `actions/upload-artifact` released v2, just follow their changeto get updated and secure. No migration is needed.

Update actions in workflows

---

build.gradle

Recently, Checker Framework builds started failing with an error about encodings in JSpecify files:
````
> Task :javadoc FAILED
/__w/1/jspecify/src/main/java/org/jspecify/nullness/NullUnmarked.java:44: error: unmappable character (0xE2) for encoding US-ASCII
* <p>Otherwise it is considered null-unmarked: whether that???s because it is more narrowly enclosed
^
/__w/1/jspecify/src/main/java/org/jspecify/nullness/NullUnmarked.java:44: error: unmappable character (0x80) for encoding US-ASCII
* <p>Otherwise it is considered null-unmarked: whether that???s because it is more narrowly enclosed
^
/__w/1/jspecify/src/main/java/org/jspecify/nullness/NullUnmarked.java:44: error: unmappable character (0x99) for encoding US-ASCII
* <p>Otherwise it is considered null-unmarked: whether that???s because …
```

Set javadoc encoding

---

.github/workflows/build.yml

I'm hoping that this will address [a sporadic(?)
failure](https://github.com/cpovirk/jspecify/runs/7975247419):
```
Could not open settings generic class cache for settings file '/home/runner/work/jspecify/jspecify/settings.gradle' (/home/runner/.gradle/caches/7.5.1/scripts/8fxsx7a5az16qabak9o2v29h1).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
```
Gradle doesn't clearly support Java 19 yet:
https://docs.gradle.org/current/userguide/compatibility.html
I'm basing this config on [similar configuration in Error
Prone](https://github.com/google/error-prone/blob/f94a04d407583bc9f85847089d72298deecf6fb0/.github/workflows/ci.yml#L23).

Mark 19-ea as experimental.

---

docs/src/pages/about.md

Tried to turn the "about page" into more specifically an "about us" page. In the process I didn't quite feel like nuking the "what are we trying to do" text. It does seem like it belongs somewhere else, but I didn't want to try to solve that problem yet.

revise about page

---

docs/docusaurus.config.js
docs/src/pages/index.js

I'm still using tool-independent in a couple places where it seems like it wants to be more descriptive.

Switch back to Standard (from Tool-Independent) in titles

---

docs/src/pages/about.md

* The company public name changed from SonarSource to Sonar in 2022
* Add distinct links for the 3 tools

Update Sonar references in 'about' page

---

src/java9/java/module-info.java

We'll want to clean this up as part of
https://github.com/jspecify/jspecify/issues/350, too.

Export both old and new packages from the module.

---

.github/workflows/build.yml

We expect that this works after
https://github.com/jspecify/jspecify/pull/358
It does appear that the 19-ea job has passed since then. That said, the
error was flaky, not a consistent failure, and thus the most recent
dozen-plus runs _before_ that PR had passed, too. Still, let's try this
and see how it goes.
This will hopefully wrap up our work on
https://github.com/jspecify/jspecify/issues/320.

Add JDK19 (non-Early Access) as a non-experimental CI job.

---

docs/docusaurus.config.js

Compare https://github.com/jspecify/jspecify/pull/324.
I notice that this makes the link open in a new tab by default, too, as
presumably is the default for "external" pages. That's not necessarily
ideal, but it's tolerable, and it's way better than a broken link :)

Fix "Draft Javadoc" link.

---

samples/PrimitiveAnnotations.java

This demonstrates the problem that
https://github.com/jspecify/nullness-checker-for-checker-framework/pull/53
fixes.

Sample for an annotation on a multidimensional primitive array.

---

.github/workflows/docs.yml
docs/docusaurus.config.js

This commit updates our docusaurus config to throw an error on invalid markdown links. I'm not certain that it will do much at all to help catch issues like #346, but it will at least make our builds stricter in general. We can disable this if it become to onerous.
This also refactors our Docs github workflow slightly to make it more modular. We check builds on PRs to main and build and deploy only on a push to main.

docs: fail builds on invalid markdown links; update action

---

build.gradle

This avoids a deprecation warning when using Gradle 8.0.

Update gradle-nexus.publish-plugin to 1.3.0

---

samples/NullUnmarkedUndoesNullMarked.java
samples/NullUnmarkedUndoesNullMarkedForWildcards.java

Companion to https://github.com/jspecify/nullness-checker-for-checker-framework/pull/62
In support of https://github.com/jspecify/nullness-checker-for-checker-framework/issues/18

Samples for `@NullUnmarked`.

---

samples/packageDefault/packagedefault/Bar.java
samples/selfType/selftype/SelfType.java

Don't merge until https://github.com/jspecify/nullness-checker-for-checker-framework/pull/68 is merged and a new PR is created just for the report updates.

Use `test:cannot-convert` in place of `jspecify_nullness_mismatch` in a few places.

---

samples/NonNullProjection.java
samples/NonNullSimple.java

The reference checker already supports these, but I've been keeping [the
relevant feature
request](https://github.com/jspecify/nullness-checker-for-checker-framework/issues/17)
open until we have proper tests.

Add samples for `@NonNull`.

---

.github/workflows/build.yml

If we make changes to the test inputs, that might cause the reference checker to fail, and later be fixed, but it shouldn't prevent merging the PR onto this repo.
Also, only run `jspecifySamplesTest` test on PRs, not merges.

Don't fail the CI if the conformance tests or samples tests fail.

---

.github/workflows/docs.yml

It's refs/heads/main, not refs/head/main.
Attempt to fix the continuous deployment issue raised in https://github.com/jspecify/jspecify/issues/411#issuecomment-1688377040

workflow: fix head ref identifier

---

.github/workflows/docs.yml

https://www.youtube.com/watch?v=6UX9Q46mNFQ
https://github.com/actions/download-artifact#compatibility-between-v1-and-v2v3

workflow: specify an intermediate path when downloading built docs

---

docs/locale/ja/LC_MESSAGES/index.po
docs/src/pages/about.md
gradle/publish.gradle

Hello jspecify team,
Last year I've retired from development of the SpotBugs core.
And recently I have less opportunity to contribute this project, so I want to remove my name from the `developers` metadata in the POM.
Also, there is no other SpotBugs teammate working on this project, so please consider to remove the SpotBugs itself from the doc.

remove Kengo and SpotBugs team from the doc

---

conformance-tests/build.gradle

Change to install `java-library` and `distribution` plugins instead of `java-library-distribution` so that there's only one distribution.

---

conformance-tests/build.gradle

This helps to decouple the builds. To be used in https://github.com/jspecify/jspecify-reference-checker/pull/123.

Put the samples files into the conformance tests zip.

---

docs/docs/spec.md

The Markdown link section missed the link to issue 260. This PR fixes it.

Add missing link to issue 260

---

conformance-tests/build.gradle
gradle/publish.gradle

Publish the snapshots, for now, to Sonatype. (Part of #299.)
Also make a consumable Gradle configuration for building locally.
https://github.com/jspecify/jspecify-reference-checker/pull/126 will use this.

Publish conformance tests to depending projects

---

.github/dependabot.yml

Dependabot by default only seems to update the npm packages: https://github.com/jspecify/jspecify/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+
Adding this configuration file hopefully updates also the gradle and github actions versions.

Configure dependabot behavior

---

.github/workflows/docs.yml

Fixes a docs build break ([example](https://github.com/jspecify/jspecify/actions/runs/7805130551/job/21288658577)).

Use upload-artifact@v4 to match download-artifact@v4.

---

samples/CaptureConvertedTypeVariableBounded.java

EISOP produces an expected error:
````
/home/runner/work/jspecify-reference-checker/jspecify-reference-checker/jspecify-reference-checker/build/conformanceTests/samples/CaptureConvertedTypeVariableBounded.java:102: (return.type.incompatible) incompatible types in return.
return p.get();
^
type of expression: capture#454 of ? extends T
method return type: Object
````

Remove `jspecify_but_expect_nothing` b/c EISOP produces an error

---

src/main/java/org/jspecify/annotations/package-info.java

Its contents were removed in
https://github.com/jspecify/jspecify/pull/511

Remove now-empty "Important warning" heading.

---

.github/workflows/build.yml
build.gradle
src/integrationTest/java/org/jspecify/annotations/NullMarkedTest.java

- Upgrade Spotless to upgrade google-java-format.
- Make nested test classes `static` so that we don't end up with
[synthetic parameters that upset our JDK-8 integration
test](https://bugs.openjdk.org/browse/JDK-8058322).
(https://errorprone.info/bugpattern/ClassCanBeStatic!)
Thanks to cushon@ for the pointers.
While there, rename a test that I should have renamed as part of
https://github.com/jspecify/jspecify/pull/270.
And update our CI versions to include JDK 21. (I haven't added JDK 22,
as we've seen some potential signs of remaining flakiness there.)

Fix a couple problems with building under JDK 22:

---

docs/docs/start-here.md

Note the actual package name (fixes #524).
Note that 1.0 is upcoming, not eventual.
Fix the link to the specification.

Update the start-here page

---

docs/docs/start-here.md
docs/docs/tool-conformance.md
docs/docs/using.md
docs/docs/whether.md

These links _usually_ work. However, if you navigate from _an external
site_ to a URL like https://jspecify.dev/docs/using, then you'll end up
at https://jspecify.dev/docs/using/ (with a trailing slash). (Links
_within_ the site apparently get intercepted to load the content and
update the URL through the magic of JavaScript, thereby avoiding this
problem. Compare https://github.com/jspecify/jspecify/issues/411 and
friends.)
Anyway, once you're at https://jspecify.dev/docs/using/, links like
those in "see if the caveats about Kotlin or annotation processors apply
to your situation" are broken... sometimes. If you right-click and "Open
link in new tab," they work fine. (The browser sees a link to
https://jspecify.dev/docs/whether#kotlin, for example.) However, as soon
as you left-click one …

Fix half-broken links.

---

docs/docusaurus.config.js

The resulting URLs look less clean, but they will be more consistent
and, more importantly, more reliable.
To recap:
- GitHub Pages adds a trailing slash if you navigate directly to a URL
from an external source. See my discussion in
https://github.com/jspecify/jspecify/pull/577, and see the table at
https://github.com/slorber/trailing-slash-guide?tab=readme-ov-file#summary.
- Docusaurus currently does _not_ add a trailing slash during intra-site
navigation. This leads to inconsistent results that depend on the
source of the link. And that makes it easy for links to be broken in
some cases but us not to notice—nor Docusaurus to report an error.
- This PR makes Docusaurus add a trailing slash. See
https://docusaurus.io/docs/api/docusaurus-config#trailingSlash.

Add trailing slashes to URLs.

---

samples/CaptureAsInferredTypeArgument.java
samples/CaptureConvertedToObject.java
samples/CaptureConvertedToObjectUnspec.java
samples/CaptureConvertedToOther.java
samples/CaptureConvertedToOtherUnspec.java
samples/CaptureConvertedTypeVariableBounded.java
samples/ContainmentExtends.java
samples/DereferenceIntersection.java
samples/NotNullMarkedContainmentExtends.java
samples/NotNullMarkedTypeVariableBound.java
samples/NotNullMarkedUseOfWildcardAsTypeArgument.java
samples/UseOfTypeVariableAsTypeArgument.java

This makes `NullSpecTest$Strict` go from having 180 unexpected
diagnostics to having 146.

Remove `jspecify_but_...` where incorrect behavior has been fixed.

---

.github/dependabot.yml

Compare https://github.com/google/truth/pull/1304
This would presumably have avoided the problem discussed in
https://github.com/jspecify/jspecify/pull/598.

Perform dependency updates in weekly batches.

---

build.gradle
gradle/integration-test.gradle

Running it is good practice, but running it has also gotten more complex
now that Error Prone depends on JSpecify.
Luckily, there is only so much that we can mess up in the declarations
of the annotations (and only a little more than that once you include
the integration tests).
(Please don't think too hard about the fact that Error Prone is
currently producing legitimate InvalidBlockTag and
UnrecognisedJavadocTag warnings because we're using a JDK11 toolchain
for Javadoc at the moment....)
Fixes https://github.com/jspecify/jspecify-reference-checker/issues/202

Stop running Error Prone.

---

docs/docs/spec.md

Many style guides recommend this: https://www.masterclass.com/articles/when-to-spell-out-numbers-explained.
I found it jarring to read the numerals.

Use words instead of digits in sentences

---

docs/docs/spec.md

- Use "output" consistently instead of a mix of that and "result." This
is also more consistent with "input."
- Mention another case in which we're likely to require that checkers
implement the all-worlds version of a rule.

Phrasing and non-normative changes to Substitution.

---

docs/docs/spec.md

These concepts let us:
- consolidate the differences between existing "all-worlds" and "some-world" versions of rules (and this PR does so)
- avoid introducing many more such differences when we begin treating `UNSPECIFIED` as "maybe `MINUS_NULL`" for  https://github.com/jspecify/jspecify/issues/248
- give relatively clear names to concepts that I have previously been tempted to give [unclear names to](https://github.com/jspecify/jspecify-reference-checker/blob/db89327f9fc984f3689f8a9c8df40817fe8d0790/src/main/java/com/google/jspecify/nullness/NullSpecAnnotatedTypeFactory.java#L611-L618)

Introduce the concepts of "comfortable" and "worried."

---

docs/docs/spec.md

Not that we're done updating the spec for 1.0.0 decisions yet. But we
won't merge the `specification-1.0` branch into `main` until we are.

Remove warning about not reflecting 1.0.0 decisions.

---

docs/docs/spec.md

This PR addresses two comments from @netdpb:
- We now cite a JLS concept of "same type."
- For `A` to a JSpecify subtype of `F`, we now require that the
corresponding *base* types pass the Java subtyping test.
Also, it sneaks in some real em dashes, which I'm guessing got converted
to `---` at some point under the assumption that that would be rewritten
by doc tooling to an em dash... after which I guess that assumption got
violated?

Improve discussion of subtyping and same-type rules.

---

docs/docs/spec.md

This rule is written such that a Kotlin class _would_ still be treated
as null-marked _if_ it (or an enclosing class) were annotated with
`@NullMarked`. That enables a user to annotate it if desired, but more
importantly, it allows a future version of Kotlin to produce that
annotation automatically.
Fixes https://github.com/jspecify/jspecify/issues/611
~This rule is written such that a Kotlin class _would_ still be treated
as null-marked _if_ it were annotated with `@NullMarked`. That enables a
user to annotate it if desired, but more importantly, it allows a future
version of Kotlin to produce that annotation automatically.~
~Still, we are likely to want to revisit this rule, especially if Kotlin
begins generating `@NullMarked`. In particular, as [noted by …

Treat Kotlin code as null-unmarked.

---

docs/docs/spec.md

Clarify that when a type is both null-inclusive under every parameterization and null-exclusive under every parameterization in an all-worlds interpretation, those are each true *in different worlds*.

Clarify all-worlds interpretation a bit

---

docs/docs/spec.md

This PR implements the "`*/*/*/*`" (aka "`String*`") option from
https://github.com/jspecify/jspecify/issues/248.
As such, we should merge it only if we decide to go that way. If we
decide to go another way, then we probably need to [make a different
change to the the
spec](https://github.com/jspecify/jspecify/issues/623#issuecomment-2341517812):
We need to do _something_ for #248 as part of
https://github.com/jspecify/jspecify/issues/623.
Assuming that we do go that way:
I think this PR changes the rules such that we never say either "If `T`
has nullness operator `UNION_NULL`..." or "If `T` has nullness operator
`MINUS_NULL`...." Instead, checks for those nullness operators always
use the "worried" and "comfortable" rules. This is part of what I
conceptually like about both these new …

Update rules for a change in `T*` substitution.

---

docs/docs/spec.md

This addresses https://github.com/jspecify/jspecify/issues/626 enough
for 1.0 purposes, but as I note in a non-normative comment in the spec,
we may want to revisit it in the future. I'll keep the bug open but
remove it from the spec-1.0 milestone.

Deem annotations in `instanceof` to be unrecognized, even in type arguments.

---

docs/docs/spec.md

This is already covered in [the
Javadoc](https://jspecify.dev/docs/api/org/jspecify/annotations/Nullable.html),
but the spec didn't cover it until now.

Make annotation element types intrinsicially non-nullable.

---

docs/docs/spec.md

See https://github.com/jspecify/jspecify/issues/301.
We should in principle say something normative. But I don't think we
want to block spec 1.0 on that, and I'd like to think that a
non-normative comment could be helpful and also quick to add...?

Give a non-normative warning about `synthetic` methods and method bodies.

---

docs/docs/spec.md

_Now_ the nullness-delegating subtyping rules for Java are easy to
understand.

Fix "no"/"not" typo.

---

docs/docs/spec.md

(I think this is in response to another two-year-old comment from
@kevinb9n.)

Clarify that we reserve _single_ capital letters for types.

---

.github/workflows/docs.yml

...since those affect the generated Javadoc.
The reason that I'm noticing this is that my
https://github.com/jspecify/jspecify/pull/648 is waiting for the "Build
Documentation" CI task to run, but it's not running on account of this
configuration that I approved back in
https://github.com/jspecify/jspecify/pull/541... :)
This PR should address that, but I wonder if the problem runs deeper: I
think that our branch-protection rules might be able to require a CI
task only _unconditionally_. So if we are trying to merge a change that
touches, say, the conformance tests, I'm thinking that GitHub might
require a documentation build for that, even though the build (a)
couldn't be affected by the change and thus (b) wouldn't be run by CI.
We can always wait to see what happens. If we have …

Run documentation build for changes to Java sources.

---

src/main/java/org/jspecify/annotations/Nullable.java

See
https://github.com/jspecify/jspecify/pull/644#issuecomment-2359409320

Expand Javadoc to cover that all parts of the `instanceof` type are unrecognized locations.

---

docs/docs/spec.md

They were already unrecognized locations for nullness annotations, but
now we also specify that they're non-nullable.
(Also, this PR includes a bit of reformatting that I'd apparently missed
in #649.)

Make enum constants intrinsically non-nullable.

---

docs/docs/spec.md

We already say this for our type-use annotations, so this PR adds
similar phrasing for our declaration annotations.
Motivation:
- Make the two sections consistent.
- Further emphasize that `@NullMarked` and `@NullUnmarked` can't appear
on fields. (Another effort that could help with that is
https://github.com/jspecify/jspecify/issues/622.) This is mostly a
future concern, since the annotations' `@Target` dosen't permit usage
on fields, but weird things might happen if we add `@Implies` someday.
- Further emphasize that `@Nullable` and `@NonNull` have no effect on
local variables, etc. (This change is a tiny step toward
https://github.com/jspecify/jspecify/issues/661.)

Clarify that tools should look for annotations only in recognized locations.

---

docs/docs/spec.md

I chose to write a rule directly about the _type usage_ that is the
parameter, rather than to write a rule that makes the whole method a
null-unmarked scope as I'd been discussing in the issue thread. I did
this so that at least the _implementation_ can remain null-marked if the
class is.
~One arguable theoretical downside to that choice is that even the
parameter's nullness-would be unspecified even in the case of:~
```
@NullMarked record Foo() {
@NullMarked public boolean equals(Object o) { ... }
}
```
~But it would _also_ be weird if the method-level `@NullMarked` _had_ an
effect, since it's otherwise redundant with the class-level annotation.
So I'm not worried about that.~
~It would be nice if there were an obvious way to have our cake and eat
it, too, when analyzing the _source …

Deem "`equals(Object o)`" in a record class to always have a nullable parameter type.

---

docs/docs/spec.md

In more formal writing, it is recommended to avoid contractions.
There was also one typo and some regularity that this PR fixes.

Expand contractions and fix typos

---

docs/docs/spec.md

And more clearly distinguish between:
- `instanceof Foo`, the "type comparison operator"
- `instanceof Foo foo`, the "pattern match operator"
(per
https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.20.2)
This prepares us for:
- possibly someday recognizing annotations in the pattern match operator
while likely still not recognizing them in the type comparison
operator, as touched on in
https://github.com/jspecify/jspecify/issues/626
- claiming to cover all of Java 22, as planned in
https://github.com/jspecify/jspecify/pull/666

Deem annotations in *all* patterns to be unrecognized.

---

docs/docs/spec.md

Because a declaration annotation with `@Target(ElementType.TYPE_PARAMETER)` can annotate type parameters.
One question about "enclosing": is it clear what the enclosing declaration of type parameters and extends or implements clauses is? The rules talk about "class member", but I'm not sure I would consider those class members.

Clarify that JSpecify declaration annotations are meant

---

docs/docs/spec.md

To check whether an expression should be dereferenced, a tool should
check whether it is null-exclusive under every parameterization. (The
spec says as much elsewhere.) But the text here could be read as
suggesting that the tool need only check the nullness operator.
Checking only the nullness operator is sufficient as long as the type
isn't a type variable. Thus, the simple fix here is to restrict the
example to a type (here, `String`) that isn't a type variable.

Make dereference example less potentially misleading.

---

docs/docs/spec.md

A newly created array, like a newly created object, is non-null. So creating a nullable array should make no sense, like creating a nullable object makes no sense.
Or am I missing what case this is covering?
I also added some non-normative examples.

Array creation is intrinsically non-null

---

docs/docs/spec.md

This builds on the work of
https://github.com/jspecify/jspecify/pull/592 in sorta kinda partially
addressing https://github.com/jspecify/jspecify/issues/580, though that
request is more about the user guide.
We do want to save most of this discussion for the user guide and
perhaps [other docs](https://github.com/jspecify/jspecify/issues/550),
but we also want to make clear that this kind of annotating is
_supported_, especially since we already call out the similar case of
varargs.
(@sdeleuze)
This PR replaces https://github.com/jspecify/jspecify/pull/670.

Touch on the syntax for annotating arrays.

---

docs/docs/spec.md

I missed the discussion of #611 and #637.
I find it a bit odd that Kotlin code is always treated as unmarked, even when it appears within a marked package/module.
Won't this lead to always requiring that Kotlin classes have `@Nullmarked`, even in a package/module that is already `@Nullmarked`?
Wouldn't this make them second-class citizens?
I'm fine with keeping the rule, but would prefer some motivation in the specification document.

Provide motivation for the `@kotlin.Metadata` rule

---

docs/docs/spec.md

I found the subset of the declaration locations where annotation locations are unrecognized confusing.
I went through [ElementType](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/annotation/ElementType.java) and list all the places that are unrecognized, in the non-normative part.
(I didn't mention "type use", that should be clear as we talk about declaration annotations.
I also found the "named class" confusing, as it seems to exclude interfaces. I'm not sure "named type" is better... The document in other places makes a distinction between class and interface, so just listing "class" here seems odd.
In some earlier document we explicitly stated that we'll use "class" for all kinds of type declarations. Maybe we should add that to this document? I have …

Expand list of declaration locations that are unrecognized

---

docs/docs/spec.md

#674 undid the change from #678.
I think this is just a merge issue, as the later text that says array creations are intrinsically non-null is still there.

Remove array creation expressions, again

---

docs/docs/spec.md

`cast` appears only once in `spec.md` before this PR.
Annotations in `instanceof` are unrecognized per #626, #668.
In #252 we decided only real sub-components of a cast expression can be annotated.
This PR contradicts what we decided in #252 and forbids annotations in both instanceof and casts.
The types in both are closely related and we should have similar rules for them.
[This comment](https://github.com/jspecify/jspecify/issues/626#issuecomment-2358825421) suggests not recognizing the instanceof usages until further discussion.
Similarly, we should re-open #252 and not recognize annotations in casts.
Or what discussion about the difference between casts and instanceofs am I forgetting? If there is a reason, a quick note in the spec would be good, as otherwise questions about cast …

Examples of annotation usages in cast expressions

---

docs/docs/spec.md

- Update "multiple worlds" non-normative text to reflect that [we also
consider the possibility of
`MINUS_NULL`](https://github.com/jspecify/jspecify/issues/248).
- Make the initial non-normative comments look like other non-normative
comments, moving the explanation of non-normative comments before most
of them.
- Join together some adjacent non-normative comments, as in
https://github.com/jspecify/jspecify/pull/657#discussion_r1769241725,
adding some transition words in one case.

My batch of nitpicking:

---

README.md
conformance-tests/build.gradle
docs/docs/start-here.md
docs/docusaurus.config.js
gradle/publish.gradle
samples/README.md
src/main/java/org/jspecify/annotations/NonNull.java
src/main/java/org/jspecify/annotations/NullMarked.java
src/main/java/org/jspecify/annotations/NullUnmarked.java
src/main/java/org/jspecify/annotations/Nullable.java
src/main/java/org/jspecify/annotations/package-info.java

I found that URLs in the official site still uses legacy URL with HTTP scheme.
Since `jspecify.org` provides no valid certificates, I suggest using `jspecify.dev` with HTTPS scheme.

Replace http://jspecify.org with https://jspecify.dev

---

.github/workflows/build.yml

- Migrates from deprecated v3 version to v4, see https://github.com/gradle/actions/blob/v4/docs/deprecation-upgrade-guide.md
- Omits redundant wrapper-validation-action which is performed by setup-gradle by default, see https://github.com/gradle/actions/blob/v4/docs/setup-gradle.md#gradle-wrapper-validation
Fixes #741 (probably)
The issue is that currently the deprecated v3 https://github.com/gradle/wrapper-validation-action is used. Recent wrapper-validation versions (including v3) have a hardcoded list of known checksums, and in that case don't need to fetch any information from the Gradle site and should not be flaky. The problem is however likely that the list of v3 is too old and does not contain the Gradle wrapper version which is currently used here (>= 8.10), so it needs to fetch …

Update Gradle actions in build workflow

---

docs/docs/using.md

As we already note in [our actual docs about
Kotlin](https://jspecify.dev/docs/whether/#kotlin), Kotlin treats
JSpecify annotations as strictly as it does JSR-305 annotations
nowadays.

Remove old reference to Kotlin caveats.

---

gradle/publish.gradle

Similar change to https://github.com/jspecify/jspecify-reference-checker/pull/220 to ensure the conformance-tests SNAPSHOT artifact is released in the new location.
The string `oss.sonatype` now doesn't appear in the repo, so hopefully this is the only place that needs this change.

Use new Sonatype Central URLs

---

conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/notnullmarked/Other.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/nullmarked/Other.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/nullunmarked/Other.java

This problem was reported by @pyltsinmikhail in
https://github.com/jspecify/jspecify/pull/765.

Fix try-with-resources tests to use `@NonNull` where expected.
