samples/AnnotatedReceiver.java
samples/UnrecognizedLocationsMisc.java

Couldn't find these elsewhere but may have missed it in all these samples.

add samples for some more forbidden type annotation locations

---

samples/README.md

* Structure comment syntax around normative vs. non-normative
* Also explain concepts where they are used, not later.
* Put the most important information first.

Refactor samples README

---

src/java9/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/NullMarked.java

Fix cross-references and formatting

---

docs/docusaurus.config.js
docs/src/pages/index.js

Nothing big here, just a homepage <meta> and a few links.

Fix a homepage description and a few links

---

src/main/java/org/jspecify/meta/Implies.java

Change `@Implies` from a repeatable annotation to one with an array of values

---

.github/workflows/build.yml
build.gradle

Don't create Javadoc before Java 15

---

docs/docs/user-guide.md
docs/docusaurus.config.js
docs/src/components/HomepageFeatures/index.js
docs/src/pages/about.md
docs/src/pages/index.js

I'm not using docusaurus (yet?)... just trying to tweak text in ways that I hope won't upset the programming.

various small web site updates

---

.idea/.gitignore
docs/docusaurus.config.js

probably needs to be an absolute link

Try to fix javadoc link from site

---

src/main/java/org/jspecify/nullness/NonNull.java
src/main/java/org/jspecify/nullness/NullMarked.java
src/main/java/org/jspecify/nullness/NullUnmarked.java
src/main/java/org/jspecify/nullness/Nullable.java

I'm still going to be revising this numerous times. I'm aware it has plenty of issues; the question is which really need to be fixed for 0.3.

first round of javadoc revisions

---

docs/src/pages/index.js

... rather than straight to the User Guide specifically.

Link the central button to a list of things to read

---

docs/docs/spec.md
docs/docs/user-guide.md
docs/src/pages/start-here.md

random tiny doc fixes

---

docs/docs/spec.md

... and make it more consistently outdated

Add warning that spec is outdated

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle to 7.6

---

.github/workflows/build.yml

Run reference checker tests on PRs

---

.github/workflows/build.yml

Run conformance/sample tests on push (post-merge).

---

conformance/Basic.java

New conformance tests will go into [`jspecify/conformance`](https://github.com/jspecify/jspecify/tree/main/conformance).
This is a basic test input just to have something there.

Create a new conformance test file in the new directory.

---

docs/docs/start-here.md

start-here page: link to reference-checker and portray it as ready

---

docs/docs/start-here.md

Fix broken Javadoc links.

---

.github/workflows/docs.yml

workflows: fix yaml syntax error

---

.github/workflows/docs.yml

workflows: checkout the repo before deploying

---

conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/notnullmarked/AnnotatedTypeParameters.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/notnullmarked/AnnotatedWildcards.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/notnullmarked/Other.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/nullmarked/AnnotatedTypeParameters.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/nullmarked/AnnotatedWildcards.java
conformance-tests/src/assertions/java/org/jspecify/conformance/tests/irrelevantannotations/nullmarked/Other.java
samples/AnnotatedTypeParameter.java
samples/AnnotatedWildcard.java
samples/NotNullMarkedAnnotatedTypeParameter.java
samples/NotNullMarkedAnnotatedWildcard.java
samples/UnrecognizedLocationsMisc.java

Also remove comment from conformance test assertions that documents which sample files are covered.

Add comment to sample files covered by conformance test assertions

---

docs/docs/user-guide.md

Just a first shot at this to get the fact somewhere in the user guide, happy to make edits

A brief note on the non-hierarchicalness of packages

---

build.gradle

Version of #498 for the `samples-google-prototype` branch.

Compile the `samples` files as tests (samples-google-prototype)

---

build.gradle
conformance-tests/build.gradle
gradle/format.gradle
gradle/integration-test.gradle
gradle/mrjar.gradle
gradle/publish.gradle
settings.gradle

I used the date of the first commit to each file for the year.

Add copyright and license info to Gradle files.

---

docs/docs/start-here.md

Based on a comment from @agentgt in #492.

Direct people to file an issue in the reference checker repo

---

docs/blog/2024-07-17-release-1.0.0.md
docs/blog/authors.yml

1.0.0 release blog post

---

docs/docs/tool-conformance.md

Will remove it from wiki afterwards.

Add conformance to docs

---

README.md
docs/blog/2024-07-17-release-1.0.0.md
docs/blog/authors.yml
docs/docs/applying.md
docs/docs/spec.md
docs/docs/start-here.md
docs/docs/using.md
docs/docs/whether.md

Please do not make any changes to this branch except via pull request onto the branch.

Update documentation for 1.0.0

---

docs/docs/using.md

For those who want to make this change, the automation will be helpful.

Mention AnnotationPosition Error Prone check to help with moving annotations

---

docs/package-lock.json
docs/package.json

Dependabot doesn't know that all the Docusaurus dependencies have to be in sync, so #595 and #596 fail.

Update Docusaurus to 3.5.2.

---

build.gradle
conformance-tests/build.gradle
settings.gradle

And break the resulting circular dependency as advised by @tbroyer in
https://github.com/jspecify/jspecify/issues/604#issuecomment-2302220782.

Upgrade Error Prone to 2.30.0.

---

docs/docs/spec.md
docs/locale/ja/LC_MESSAGES/tsttcpw.po
src/main/java/org/jspecify/annotations/NullMarked.java
src/main/java/org/jspecify/annotations/Nullable.java

```
rg -l jls/se | xargs perl -pi -e 's#jls/se\d+#jls/se22#g'
```

Bump JLS references to version 22.

---

docs/docs/spec.md

Sneak in some discussion of how we define "enclosing" perhaps somewhat
differently from how the Java compiler API does.

Update the spec for `@NullUnmarked`.

---

docs/docs/spec.md

(The formatter I have handy is a full-file formatter, so it's nice to be
able to run it on "real" PRs without accidentally including changes like
this in the resulting commit.)

Apply a Markdown formatter.

---

docs/docs/spec.md

See https://github.com/jspecify/jspecify/issues/306.

Mention that our declaration annotations are *not* recognized on record components.

---

docs/docs/spec.md

```
$ git checkout main
$ git pull
$ git checkout specification-1.0
$ git pull
$ git checkout -b specification-1.0-rebased
$ git rebase "$(git merge-base specification-1.0-rebased main)" specification-1.0-rebased --onto main
```
And then, to verify the results against a plain merge:
```
$ git checkout specification-1.0
$ git checkout --detach
$ git merge main
$ git diff specification-1.0-rebased
```
(I am aware that that is not the most direct route, but it uses primitives that I was mostly already familiar with :))

Replay specification-1.0 commits onto main branch, take two.

---

docs/docs/spec.md

Follow-up to the discussion in #667.

Reword introduction of nullness operators

---

docs/docs/spec.md

The first question about `@Nullable` is subsumed by the second question about all `nullness operators`.
If that is the case, I would only ask the general question.
If that is a mis-understanding on my side, can the questions be clarified?

Adjust motivating nullness questions

---

docs/docs/spec.md
docs/docusaurus.config.js

We may end up waiting a bit for final reviews, but let's queue this up.

Remove "draft" from the spec title.

---

docs/blog/2024-07-17-release-1.0.0.md
docs/docs/spec.md

Planned merge date: Mon Oct 21

Update docs for the release of spec 1.0.0.

---

docs/src/pages/about.md

Fixes https://github.com/jspecify/jspecify/issues/721

Change VMware to Broadcom.

---

docs/docs/whether.md

Fixes https://github.com/jspecify/jspecify/issues/731

Replace reference to an IDEA bug that has been fixed.
